# Generated by Django 5.0.1 on 2024-01-31 21:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('short_description', ckeditor.fields.RichTextField(verbose_name='Kısa Açıklama')),
                ('short_second_description', ckeditor.fields.RichTextField(verbose_name='Kısa İkinci Açıklama')),
                ('description', ckeditor.fields.RichTextField(verbose_name='İçerik Yazısı')),
                ('image', models.ImageField(upload_to='services', verbose_name='Banner Resim')),
                ('content_image', models.ImageField(upload_to='services', verbose_name='İçerik Resim')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
    ]
