# Generated by Django 5.0.1 on 2024-01-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('bio', models.TextField(verbose_name='Hakkımda')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('image', models.ImageField(upload_to='about/images/', verbose_name='Profil Fotoğrafı')),
            ],
            options={
                'verbose_name': 'Hakkımda',
                'verbose_name_plural': 'Hakkımda',
            },
        ),
    ]
