# Generated by Django 5.0.1 on 2024-01-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Randevu',
        ),
        migrations.DeleteModel(
            name='Yorum',
        ),
    ]
